### ISSUE TITLE
Sometimes the terminal gets "messed up" and requires a `reset`

### ISSUE THREAD

**Issue by rmcgibbo** [samueldr/nix-top#8]
Some discussion: https://logs.nix.samueldr.com/nixos-chat/2021-02-24#1614205429-1614205735;

I'm not quite sure what conditions are sufficient to trigger this, but I observe it from time to time.

**Comment by ncfavier** [comment]
When pressing `^C` while control flow is between [lines 155 and 157](https://github.com/samueldr/nix-top/blob/5957ccca1a76abf10dffea53641862306d8571db/nix-top#L155-L157), you get a terminal in raw mode. Working on fixing this.
